# Generated by Django 4.0.1 on 2022-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Done',
        ),
    ]
